php:
  preset: laravel
  disabled:
    - unused_use
  finder:
  exclude:
    - "modules"
    - "node_modules"
    - "storage"
    - "vendor"
  name: "*.php"
  not-name:
    - "*.blade.php"
    - "_ide_helper.php"

js: false
ts: false
css: false
vue: false
py: false
